# -*- coding: utf-8 -*-
"""covid 19 india status.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dg3L2zhKgK9cVH7jz8lNQum1wf5ye17g
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('darkgrid')

df=pd.read_csv("/content/latest Covid-19 India Status1.csv")

df

df.info()

df.shape

df.describe()

df.describe(include=object)

df.describe(include=float)

df.isnull().sum()

df.columns

# rename the columns
df.columns=['State','Total_Cases','Active','Deaths','Active_Ratio','Death_Ratio']

df.head(1)

df.groupby(['State'])['Active_Ratio'].agg(["max"]).sort_values(by='max', ascending=False)

plt.figure(figsize=(10,4))
plt.plot(df['State'],df['Active_Ratio'],color='purple',marker='o')

plt.xticks(rotation=90,fontsize=13.5)
plt.yticks(fontsize=13.5)

plt.xlabel('State', fontsize=15)
plt.ylabel('Active Ration', fontsize=15)

plt.title("Line Plot for Active Ratio",fontsize=15)
plt.show()

# total cases in each state
total_cases_state= df.groupby('State')['Total_Cases'].sum().sort_values(ascending=False)

total_cases_state

total_cases_state.index

plt.figure(figsize=(15, 8));
plt.xticks(rotation=75)
sns.barplot(x=total_cases_state.index, y=total_cases_state);

plt.title('Total Cases in Each State', fontsize=20);
plt.xlabel('State', fontsize=30)
plt.ylabel('Total Cases', fontsize=15);
plt.show()

import warnings
warnings.filterwarnings("ignore")

# Top 10 state total cases
top10=total_cases_state[:10]
plt.figure(figsize=(15, 10));
plt.xticks(rotation=75)

sns.barplot(x=top10.index, y=top10);

plt.title('Total Cases in Top 10 States', fontsize=20);
plt.xlabel('State', fontsize=30)
plt.ylabel('Total Cases', fontsize=15);
plt.show()

plt.figure(figsize=(10,4))
plt.plot(df['State'],df['Active_Ratio'],color='purple',marker='o', label='Active_ratio')

plt.xticks(rotation=90,fontsize=13.5)
plt.yticks(fontsize=13.5)

plt.xlabel('State', fontsize=15)
plt.ylabel('Active Ration', fontsize=15)

plt.title("Line Plot for Active Ratio",fontsize=15)

plt.plot(df['State'],df['Death_Ratio'], color='blue',marker='*', label='deaths')
plt.legend()
plt.show()

# pie chart shows distrinbution
# pie chart of total cases in top 5 states in india

plt.figure(figsize=(8,8))

plt.pie(x='Active', data=df.head(), labels='State', autopct='%.1f%%')
plt.title("Active Cases in Top 5 states in India", fontsize = 24)
plt.show()

plt.figure(figsize=(7,7))
labels = df.index
plt.pie(x='Total_Cases', data=df.head(15), labels='State', startangle=90,autopct='%.1f%%')
plt.title("Total Cases in Top 5 states in India", fontsize = 24)
plt.tight_layout()
plt.show()

df.head(1)

Recovered= df['Total_Cases']- df['Active']- df['Deaths']

Recovered

df['Recoverd_cases']= Recovered

df.head()